package com.wkq.database.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EXCEPTION_INFO".
 */
@Entity
public class ExceptionInfo {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String ErrorTag;

    @NotNull
    private String ErrorMessage;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public ExceptionInfo() {
    }

    public ExceptionInfo(Long id) {
        this.id = id;
    }

    @Generated
    public ExceptionInfo(Long id, String ErrorTag, String ErrorMessage) {
        this.id = id;
        this.ErrorTag = ErrorTag;
        this.ErrorMessage = ErrorMessage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getErrorTag() {
        return ErrorTag;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setErrorTag(@NotNull String ErrorTag) {
        this.ErrorTag = ErrorTag;
    }

    @NotNull
    public String getErrorMessage() {
        return ErrorMessage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setErrorMessage(@NotNull String ErrorMessage) {
        this.ErrorMessage = ErrorMessage;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
