package com.wkq.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EXCEPTION_INFO".
*/
public class ExceptionInfoDao extends AbstractDao<ExceptionInfo, Long> {

    public static final String TABLENAME = "EXCEPTION_INFO";

    /**
     * Properties of entity ExceptionInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ErrorTag = new Property(1, String.class, "ErrorTag", false, "ERROR_TAG");
        public final static Property ErrorMessage = new Property(2, String.class, "ErrorMessage", false, "ERROR_MESSAGE");
    }


    public ExceptionInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ExceptionInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EXCEPTION_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ERROR_TAG\" TEXT NOT NULL ," + // 1: ErrorTag
                "\"ERROR_MESSAGE\" TEXT NOT NULL );"); // 2: ErrorMessage
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EXCEPTION_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ExceptionInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getErrorTag());
        stmt.bindString(3, entity.getErrorMessage());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ExceptionInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getErrorTag());
        stmt.bindString(3, entity.getErrorMessage());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ExceptionInfo readEntity(Cursor cursor, int offset) {
        ExceptionInfo entity = new ExceptionInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // ErrorTag
            cursor.getString(offset + 2) // ErrorMessage
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ExceptionInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setErrorTag(cursor.getString(offset + 1));
        entity.setErrorMessage(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ExceptionInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ExceptionInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ExceptionInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
