package com.wkq.database.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MOVE_DB_DATA_HITORY".
 */
@Entity
public class MoveDbDataHitory {

    @Id
    private String key;

    @NotNull
    private String data;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MoveDbDataHitory() {
    }

    public MoveDbDataHitory(String key) {
        this.key = key;
    }

    @Generated
    public MoveDbDataHitory(String key, String data) {
        this.key = key;
        this.data = data;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    @NotNull
    public String getData() {
        return data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData(@NotNull String data) {
        this.data = data;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
