package com.wkq.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOVE_DB_DATA_HITORY".
*/
public class MoveDbDataHitoryDao extends AbstractDao<MoveDbDataHitory, String> {

    public static final String TABLENAME = "MOVE_DB_DATA_HITORY";

    /**
     * Properties of entity MoveDbDataHitory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Key = new Property(0, String.class, "key", true, "KEY");
        public final static Property Data = new Property(1, String.class, "data", false, "DATA");
    }


    public MoveDbDataHitoryDao(DaoConfig config) {
        super(config);
    }
    
    public MoveDbDataHitoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOVE_DB_DATA_HITORY\" (" + //
                "\"KEY\" TEXT PRIMARY KEY NOT NULL ," + // 0: key
                "\"DATA\" TEXT NOT NULL );"); // 1: data
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOVE_DB_DATA_HITORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MoveDbDataHitory entity) {
        stmt.clearBindings();
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
        stmt.bindString(2, entity.getData());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MoveDbDataHitory entity) {
        stmt.clearBindings();
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(1, key);
        }
        stmt.bindString(2, entity.getData());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public MoveDbDataHitory readEntity(Cursor cursor, int offset) {
        MoveDbDataHitory entity = new MoveDbDataHitory( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // key
            cursor.getString(offset + 1) // data
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MoveDbDataHitory entity, int offset) {
        entity.setKey(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setData(cursor.getString(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(MoveDbDataHitory entity, long rowId) {
        return entity.getKey();
    }
    
    @Override
    public String getKey(MoveDbDataHitory entity) {
        if(entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MoveDbDataHitory entity) {
        return entity.getKey() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
