package com.wkq.database.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "MOVE_SEARCH_HISTORY".
 */
@Entity
public class MoveSearchHistory {

    @Id
    private String moveName;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public MoveSearchHistory() {
    }

    @Generated
    public MoveSearchHistory(String moveName) {
        this.moveName = moveName;
    }

    public String getMoveName() {
        return moveName;
    }

    public void setMoveName(String moveName) {
        this.moveName = moveName;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
