package com.wkq.database.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "USER_INFO".
 */
@Entity
public class UserInfo {

    @Id
    private String userID;

    @NotNull
    private String userPhoneNum;

    @NotNull
    private String userPwd;

    @NotNull
    private String userIMEI;

    @NotNull
    private String userState;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public UserInfo() {
    }

    public UserInfo(String userID) {
        this.userID = userID;
    }

    @Generated
    public UserInfo(String userID, String userPhoneNum, String userPwd, String userIMEI, String userState) {
        this.userID = userID;
        this.userPhoneNum = userPhoneNum;
        this.userPwd = userPwd;
        this.userIMEI = userIMEI;
        this.userState = userState;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    @NotNull
    public String getUserPhoneNum() {
        return userPhoneNum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserPhoneNum(@NotNull String userPhoneNum) {
        this.userPhoneNum = userPhoneNum;
    }

    @NotNull
    public String getUserPwd() {
        return userPwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserPwd(@NotNull String userPwd) {
        this.userPwd = userPwd;
    }

    @NotNull
    public String getUserIMEI() {
        return userIMEI;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserIMEI(@NotNull String userIMEI) {
        this.userIMEI = userIMEI;
    }

    @NotNull
    public String getUserState() {
        return userState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserState(@NotNull String userState) {
        this.userState = userState;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
